# -*- coding: utf-8 -*-
"""project4_nlp.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18DtZwLDbwcTvJgxxokiPjbcF2ok7vj7b
"""

import pandas as pd
import numpy as np
import re
import nltk
import matplotlib.pyplot as plt

from nltk.corpus import stopwords
from collections import Counter
from wordcloud import WordCloud

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

nltk.download("stopwords")

data = {
    "Email": [

        "Congratulations! You have won a free iPhone. Click here now.",
        "Meeting is scheduled tomorrow at 10 AM.",
        "Claim your cash prize immediately.",
        "Project presentation has been postponed.",
        "Limited time offer. Buy now and save money.",
        "Please find the attached report.",
        "Win a lottery worth one million dollars.",
        "Lunch meeting at 1 PM today.",
        "Exclusive deal just for you. Hurry up.",
        "Can we discuss the assignment today?"

    ],

    "Label":[

        "Spam",
        "Ham",
        "Spam",
        "Ham",
        "Spam",
        "Ham",
        "Spam",
        "Ham",
        "Spam",
        "Ham"

    ]
}

df = pd.DataFrame(data)

print(df)

stop_words = set(stopwords.words("english"))

def clean_text(text):

    text = text.lower()

    text = re.sub(r'[^a-zA-Z\s]', '', text)

    words = text.split()

    words = [word for word in words if word not in stop_words]

    return " ".join(words)

df["Clean_Email"] = df["Email"].apply(clean_text)

print(df)

df["Target"] = df["Label"].map({
    "Ham":0,
    "Spam":1
})

print(df)

vectorizer = TfidfVectorizer()

X = vectorizer.fit_transform(df["Clean_Email"])

y = df["Target"]

X_train, X_test, y_train, y_test = train_test_split(

    X,
    y,

    test_size=0.2,

    random_state=42

)

model = MultinomialNB()

model.fit(X_train,y_train)

prediction = model.predict(X_test)

print("Accuracy")

print(accuracy_score(y_test,prediction))

print()

print(classification_report(y_test,prediction))

print()

print(confusion_matrix(y_test,prediction))

all_words = " ".join(df["Clean_Email"])

word_list = all_words.split()

word_freq = Counter(word_list)

print("Top Common Words")

print(word_freq.most_common(10))

spam = df[df["Label"]=="Spam"]

spam_words = " ".join(spam["Clean_Email"])

spam_counter = Counter(spam_words.split())

print("Most Frequent Spam Words")

print(spam_counter.most_common(10))

count = df["Label"].value_counts()

plt.figure(figsize=(6,5))

plt.bar(count.index,count.values)

plt.title("Spam vs Ham Emails")

plt.xlabel("Email Type")

plt.ylabel("Count")

plt.show()

wordcloud = WordCloud(

    width=800,

    height=400,

    background_color="white"

).generate(all_words)

plt.figure(figsize=(10,5))

plt.imshow(wordcloud)

plt.axis("off")

plt.title("Email Word Cloud")

plt.show()

spam_count = len(df[df["Label"]=="Spam"])

ham_count = len(df[df["Label"]=="Ham"])

print("Email Spam Detection Report")
print("---------------------------")

print("Total Emails :",len(df))

print("Spam Emails :",spam_count)

print("Ham Emails :",ham_count)

print()

print("Most Common Spam Words")

for word,count in spam_counter.most_common(5):

    print("-",word)

print()

print("Recommendation")

print("Automatically block suspicious emails containing promotional words such as free, win, prize, lottery, offer, and click.")